default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: <%= ENV.fetch('DB_HOST', 'localhost')%>
  username: <%= ENV.fetch('DB_USERNAME', 'root')%>
  password: <%= ENV.fetch('DB_PASSWORD', 'root')%>
#  port: 5432
  template: <%= ENV.fetch('DB_TEMPLATE', 'template1')%>


development:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'paranoya')%>_development

test:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'paranoya')%>_test

production:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'paranoya')%>_production

staging:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'paranoya')%>_staging
