default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  username: postgres
  password: <%= ENV.fetch('DB_PASSWORD', 'postgres')%>
  port: 5432
  #template: template0

development:
  <<: *default
  database: paranoya

test:
  <<: *default
  database: paranoya_test

production:
  <<: *default
  database: paranoya_production

staging:
  <<: *default
  database: paranoya_staging

